"""initial schema

Revision ID: 9aa9d6437404
Revises: 
Create Date: 2026-08-20 15:25:48.272117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9aa9d6437404'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('creator_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_account_id', sa.String(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('daily_upload_cap', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'external_account_id', name='uq_creator_account_identity')
    )
    op.create_table('stream_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_object_key', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'ingesting', 'ingested', 'failed_ingest', 'transcribing', 'transcribed', 'failed_transcription', 'segmenting', 'segmented', 'failed_segmentation', 'scoring', 'scored', 'failed_scoring', 'rendering', 'ready_for_review', 'failed_rendering', 'archived', name='stream_job_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('max_clips', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stream_jobs_user_status', 'stream_jobs', ['user_id', 'status'], unique=False)
    op.create_table('candidate_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stream_job_id', sa.UUID(), nullable=False),
    sa.Column('start_seconds', sa.Numeric(), nullable=False),
    sa.Column('end_seconds', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending_score', 'scored', 'selected', 'rejected', name='candidate_status'), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_annotation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_seconds > start_seconds', name='ck_candidate_segment_end_after_start'),
    sa.ForeignKeyConstraint(['stream_job_id'], ['stream_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate_segments_job', 'candidate_segments', ['stream_job_id', 'status'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stream_job_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stream_job_id'], ['stream_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stream_job_id', name='uq_transcript_stream_job')
    )
    op.create_table('rendered_clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_segment_id', sa.UUID(), nullable=False),
    sa.Column('stream_job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'rendering', 'rendered', 'failed', name='render_status'), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Numeric(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('flag_reasons', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_segment_id'], ['candidate_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_job_id'], ['stream_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rendered_clips_job_status', 'rendered_clips', ['stream_job_id', 'status'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rendered_clip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'skipped', name='review_decision_value'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rendered_clip_id'], ['rendered_clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_decisions_clip_time', 'review_decisions', ['rendered_clip_id', 'decided_at'], unique=False)
    op.create_table('upload_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rendered_clip_id', sa.UUID(), nullable=False),
    sa.Column('creator_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'uploading', 'uploaded', 'failed', 'blocked', name='upload_status'), nullable=False),
    sa.Column('target_mode', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('external_post_id', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_account_id'], ['creator_accounts.id'], ),
    sa.ForeignKeyConstraint(['rendered_clip_id'], ['rendered_clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_tasks_account_created', 'upload_tasks', ['creator_account_id', 'created_at'], unique=False)
    op.create_table('upload_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_task_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_task_id'], ['upload_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_audit_log_task', 'upload_audit_log', ['upload_task_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_upload_audit_log_task', table_name='upload_audit_log')
    op.drop_table('upload_audit_log')
    op.drop_index('idx_upload_tasks_account_created', table_name='upload_tasks')
    op.drop_table('upload_tasks')
    op.drop_index('idx_review_decisions_clip_time', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index('idx_rendered_clips_job_status', table_name='rendered_clips')
    op.drop_table('rendered_clips')
    op.drop_table('transcripts')
    op.drop_index('idx_candidate_segments_job', table_name='candidate_segments')
    op.drop_table('candidate_segments')
    op.drop_index('idx_stream_jobs_user_status', table_name='stream_jobs')
    op.drop_table('stream_jobs')
    op.drop_table('creator_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Manually added: op.drop_table() does not drop the Postgres ENUM types
    # it implicitly created (they're bound to metadata, not to any one
    # table), so without this, re-running upgrade after a downgrade fails
    # with "type already exists". Order doesn't matter here since all
    # dependent tables are already gone.
    bind = op.get_bind()
    sa.Enum(name='upload_status').drop(bind, checkfirst=True)
    sa.Enum(name='review_decision_value').drop(bind, checkfirst=True)
    sa.Enum(name='render_status').drop(bind, checkfirst=True)
    sa.Enum(name='candidate_status').drop(bind, checkfirst=True)
    sa.Enum(name='stream_job_status').drop(bind, checkfirst=True)
